name: imademyselfboss
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.27837
title: i made myself boss
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.125
  lightness: 0.49652410950511694
  saturation: 0.2843233556486666
  rhythmicContrast: 0.37241151207126677
purpose: []
